version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn lint

workflows:
  version: 2
  workflow:
    jobs:
      - test
