version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run linter
          command: yarn lint
  coverage:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests for coverage
          command: yarn test --coverage
      - run:
          name: Collect coverage
          command: |
            yarn add coveralls
            ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

workflows:
  version: 2
  workflow:
    jobs:
      - test
      - coverage:
          filters:
            branches:
              only: /^(?!pull\/).*$/
          requires:
            - test
